### ISSUE TITLE
iOS server socket dies on screen lock

### ISSUE THREAD

**Issue by oscahie** [robbiehanson/CocoaHTTPServer#10]
It seems the server socket is dying when a device with iOS 5+ goes to sleep. This is easily reproducible with the iPhoneHTTPServer project. Just run it with the default configuration (connected to a WiFi network to verify that the server is reachable), then lock the device (the app can be in the foreground or in the background, doesn't matter) and unlock it again. Try to connect to the web server and the connection will be refused.

**Comment by asielgil88** [comment]
> * on applicationDidEnterBackground: I stop the HTTP server
> * on applicationWillEnterForeground: I start the HTTP server

Hi any example or doc, on how to achieve this?
