### ISSUE TITLE
Bonjour announcing not working iOS8

### ISSUE THREAD

**Issue by spameater** [robbiehanson/CocoaHTTPServer#118]
I looks like the Bonjour announcing does not work on iOS8 anymore. The service can be discovered but when trying to resolve the service: 

[serverService setDelegate:self];
[serverService resolveWithTimeout:30.0];

I get a net service error:
- (void)netService:(NSNetService *)sender didNotResolve:(NSDictionary *)errorDict
  
  NSNetServicesErrorCode = "-72007";
  NSNetServicesErrorDomain = 10;

It works perfectly using iOS7. Using Bonjour Browser on the Mac I get the same result. The service is found but cannot be resolved.

I just tried the Apple WiTap sample and the result is the same. So this seems to be an core os issue rather than an issue with CocoaHTTPServer.

**Comment by longchuan1985** [comment]
has the bonjour issue been resolved in iOS8? I heard that in iOS9 apple recover the original mDNSResponder from DiscoveryD. But does anyone know the workaround in iOS8.

**Comment by vfernandezg** [comment]
Hi, I'm having the same problem. Any news of this?

**Comment by davidgoli** [comment]
:+1:

**Comment by romuye123** [comment]
Hello, 
I am facing the same problem. I am not even able to discover the services.
It works perfectly fine on iOS 9/10. 

Any workaround for iOS 8 ???

**Comment by xuhongfei** [comment]
Hello,
I used CocoaHTTPServer to setup my local server. But, it just can access by 127.0.0.1:port.What should i do to let it can access by www.mywebsite.com?
