### ISSUE TITLE
iPhoneHTTPServer Sample working on simulator but not on device.

### ISSUE THREAD

**Issue by igorcarrasco** [robbiehanson/CocoaHTTPServer#68]
Greetings I have implemented this in an iPhone App but neither my App nor the Sample iPhoneHTTPServer work for the device, they do work in the simulator though.

When I use the wifiIP:port on my Mac(using any browser) which is on the same network of the iPhone it simply won't open the Page, but it doesn t give a 404 error either. Its like the page is there but it can't connect.

"Unable to connect" "Firefox can't establish a connection to the server at 192.168.0.102:52395."
"The site could be temporarily unavailable or too busy. Try again in a few
    moments.
  If you are unable to load any pages, check your computer's network
    connection.
  If your computer or network is protected by a firewall or proxy, make sure
    that Firefox is permitted to access the Web."

Any idea what might be causing this? I know I have to disable my Mac OS X firewall when I want to share a website on the local network is there something similar for the iPhone App?

thanks

**Comment by victaie** [comment]
I had the same problem and I have tried all the steps mentioned in this issue, but it still doesn't work. I'm sure i have config the server correctly.
